//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_OperationByMeUsingJqueryAjaxMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POR_Employee
    {
        public long EmployeeId { get; set; }
        public string EmployeeCode { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FullName { get; set; }
        public string CallName { get; set; }
        public int CompanyID { get; set; }
        public int OrgStructureID { get; set; }
        public int DesignationStuctureID { get; set; }
        public string Address { get; set; }
        public string HomeContactNo { get; set; }
        public string MobileNo { get; set; }
        public string Email { get; set; }
        public string NIC { get; set; }
        public string Gender { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Image { get; set; }
        public Nullable<int> JobCategoryID { get; set; }
        public Nullable<int> JobGradeID { get; set; }
        public Nullable<int> EmploymentTypeID { get; set; }
        public Nullable<int> EmploymentGradeID { get; set; }
        public string EmergencyContactPerson { get; set; }
        public string EmergencyContactNo { get; set; }
        public string PostalCode { get; set; }
        public System.DateTime RecruitementDate { get; set; }
        public Nullable<System.DateTime> ConfirmationDate { get; set; }
        public Nullable<System.DateTime> SecondReqruitmentDate { get; set; }
        public string PreviousEmployeeNo { get; set; }
        public bool Active { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> ResignDate { get; set; }
        public Nullable<int> InactiveStatus { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateUser { get; set; }
        public string PassportNo { get; set; }
        public Nullable<System.DateTime> PassPortExpiryDate { get; set; }
        public string VisaNo { get; set; }
        public Nullable<System.DateTime> VisaExpiryDate { get; set; }
        public Nullable<bool> IsExpatriate { get; set; }
        public string RelationshipOfContactPerson { get; set; }
        public string PersonalInfoChangeRequestStatus { get; set; }
        public string EPFNo { get; set; }
        public Nullable<System.DateTime> EPFNoDate { get; set; }
        public Nullable<int> BranchId { get; set; }
        public string OfficeContactNo { get; set; }
        public string EMPCard { get; set; }
        public string NameWithInitial { get; set; }
    
        public virtual DesignationStucture DesignationStucture { get; set; }
        public virtual InactiveSttatu InactiveSttatu { get; set; }
        public virtual OrganisationStructure OrganisationStructure { get; set; }
    }
}
