//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_OperationByMeUsingJqueryAjaxMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POR_UserTypes
    {
        public int UserTypeid { get; set; }
        public string UserTypeName { get; set; }
        public string UserTable { get; set; }
        public string CodeFieldName { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
