//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_OperationByMeUsingJqueryAjaxMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Time_Calender
    {
        public System.DateTime CalendarDate { get; set; }
        public int CompanyId { get; set; }
        public long DayId { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string Subject { get; set; }
        public int Day { get; set; }
        public int Month { get; set; }
        public int Year { get; set; }
        public int DayTypeId { get; set; }
        public bool Posted { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedUser { get; set; }
    
        public virtual Time_DayTypes Time_DayTypes { get; set; }
    }
}
